### ISSUE TITLE
405 Method not allowed on staging

### ISSUE THREAD

**Issue by devshane** [komuw/sewer#135]
## Which version of python are you using?

Python 3.7.6

## What operating system and version of operating system are you using?

MacOS 10.14.6

## What version of sewer are you using?

0.7.9

## What did you do? (be as detailed as you can)

Using sewer as a library, when I try to generate certificates on the staging server I get a `405 Method not allowed` error at `get_identifier_authorization`. When I use the production endpoint, the code executes normally.

I see #128 but that doesn't seem to have been resolved using the staging endpoint.

Could this potentially be related to [this deprecation](https://community.letsencrypt.org/t/acme-v2-scheduled-deprecation-of-unauthenticated-resource-gets/74380)?

## What did you expect to see/happen/not happen?

A certificate to be generated.

## What did you actually see/happen? 

```
get_acme_endpoints
get_acme_endpoints_response. status_code=200
create_certificate_key
create_csr
create_account_key
intialise_success, sewer_version=0.7.9, domain_names=['x.com'], acme_server=https://acme-staging...
get_certificate
acme_register
make_signed_acme_request
get_acme_header
get_nonce
sign_message
acme_register_response. status_code=201. response={'key': {'kty': 'RSA', 'n': 'x', 'e': 'AQAB'}, 'contact': [], 'initialIp': 'x', 'createdAt': '2020-01-23T16:25:17.443639603Z', 'status': 'valid'}
acme_register_success
apply_for_cert_issuance
make_signed_acme_request
get_acme_header
get_nonce
sign_message
apply_for_cert_issuance_response. status_code=201. response={'status': 'pending', 'expires': '2020-01-30T16:25:19.34873624Z', 'identifiers': [{'type': 'dns', 'value': 'domain.com'}], 'authorizations': ['https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/...'], 'finalize': 'https://acme-staging-v02.api.letsencrypt.org/acme/finalize/.../...'}
apply_for_cert_issuance_success
get_identifier_authorization
get_identifier_authorization_response. status_code=405. response={'type': 'urn:ietf:params:acme:error:malformed', 'detail': 'Method not allowed', 'status': 405}
Error: Unable to issue certificate. error=Error getting identifier authorization: status_code=405 response={'type': 'urn:ietf:params:acme:error:malformed', 'detail': 'Method not allowed', 'status': 405}
```

Thanks for any help.

**Comment by mmaney** [comment]
Ugh, working on this too far past bedtime, and I missed that #128 had been closed, and the report said the failure wasn't always there - must have been when they were getting ready to roll out the new authorization requirements?  As this bug shows, it was a real problem, if not quite that early.

Anyway, patch attached to message I placed in that bug (also linked above) that "works for me" for the simple case of registering and getting a single host's certificate.

**Comment by komuw** [comment]
copying Mmaney's message from https://github.com/komuw/sewer/issues/128#issuecomment-580613539 :

this is due to the announced deprecation of unsigned GET requests for most of the ACME API.  I'd forgotten this change was coming when it came time to renew some certs here, and I wanted to test the new and improved script using staging before hitting production, which of course wasn't going to happen.

I have since hacked up client.py to the point that I can run a simple, single-host certificate fetch successfully.  Patch attached, as was doing this in a detached repo... and besides, this is still a WIP.  I would expect it to apply cleanly against 0.7.9, but I did have a new, definitely not yet ready for anyone but me, dns provider because that's the one I needed to use in the local tree before I started down the path to put-as-get.

[0160-Working-for-simple-single-host-cert-run-against-stag.txt](https://github.com/komuw/sewer/files/4137985/0160-Working-for-simple-single-host-cert-run-against-stag.txt)

**Comment by komuw** [comment]
hi @mmaney If you can send in a pull request with a fix; I would be happy to apply it.   

I no longer use `sewer`(not because I found something else, rather because I no longer need certificates) and so it is difficult for me to discover this bugs.

**Comment by komuw** [comment]
On a related note, if anyone wants to get commit rights to this repository; just let me know. 

Of course you must have already contributed to this repo previously, before I can grant you commit rights

**Comment by mmaney** [comment]
I don't consider it ready to pull yet.  One issue is that I'm still trying to sort out what that empty payload for post-as-get is _really_ supposed to be.  I found an errata comment that makes me think what I have there now works only because of luck.  Too much design by trial & error.  :-(

**Comment by devshane** [comment]
@mmaney Would you consider opening a WIP PR? I can help testing the branch here.

**Comment by mmaney** [comment]
Just got the current code, rebased onto 0.8.0, uploaded and issued a pull. :-)

**Comment by mmaney** [comment]
I'm not going to update this until I've looked it over again when wide awake, but I believe I have sorted out the post_as_get payload mystery.  Apparently the trick is that although it makes sense for make_signed_acme_request to jsonify the passed-in payload before base64 encoding, that jsonification step is not always required... and in fact that breaks post_as_get, as I found when I was first working on it.

So one thing I want to look at is what differences are left between post_as_get and make_signed_acme_request, and whether it makes sense to try to combine them. perhaps hoisting the json.dumps() into the callers that need it?  Oh, and stringfy... would it be cleaner (and not too repetitive) to decode utf-8 where the byte string comes from, rather than this catch-all patch?  (which assumes a struct without any nesting, and I'm nearly certain I saw at least one payload that was, or could be, nested in rfc8555.)

**Comment by mmaney** [comment]
I have finally stared at the various RFCs long enough to see that I'd been stuck on the way the existing code called the unjsonified dicts `payload`, whereas when the spec says *payload* it's referring to what make_signed_acme_request gets when it does `json.dumps(payload)`.  Except for this new post-as-get thing, where the *payload* is just an empty string, not jsonified.  This part is now clear, and agrees with testing against staging.  So it was bad luck that I tried it with un-b64'd `payload' first, and that staging laxly accepted it.

Oops, I revised the correction right out of this message.  For post_as_get, it should have (in terms of the existing code) `payload64 = self.calculate_safe_base64("")` and `payload64` should be used in forming both `signature` and the `data` items.  I don't think I've pushed that correction yet, but since staging works with my not-quite-correct-per-RFC hack, I'll let that go until I have more ready to go.  Hopefully until I can get it running against pebble...

**Comment by kylejohnson** [comment]
@mmaney Have you made any more progress on this?

**Comment by mmaney** [comment]
No, sorry.  Life has just gotten overfull, and IIRC the next step was going to be looking at all the places that initiate ACME requests and sort out how to reconcile post_as_get with make_signed_acme_request to reduce duplicated code.  One part I'm pretty sure will change is to push the jsonification of the payload back into the callers (not a great many of them) which makes it easier to refactor and recombine the two methods.

Predictions are hard, but I hope to free up time, maybe whole days, in a couple weeks.  My local work is now built on top of the [smart-nonces](https://github.com/komuw/sewer/pull/144), so testing and comments on those small patches would help push this along.

**Comment by mmaney** [comment]
@devshane @kylejohnson I forgot to reference this in PR #174, which finally closes this.
