### ISSUE TITLE
No dns_provider_name on several DNS provider classes

### ISSUE THREAD

**Issue by itavero** [komuw/sewer#146]
## Which version of python are you using?
Python 3.6.5

## What operating system and version of operating system are you using?
FreeBSD 11.2

## What version of sewer are you using?
0.7.3

## What did you do? (be as detailed as you can)
In my script I scan for all the subclasses of `sewer.BaseDns` and use the `dns_provider_name` as a key for the configuration of my tool.

## What did you expect to see/happen/not happen?
My script expects the attribute `dns_provider_name` to be present in all the subclasses with a unique name.

## What did you actually see/happen? 
The following classes do not have this attribute:
* `AliyunDns`
* `HurricaneDns`
* `RackspaceDns`          

## What is it that you would like to propose to add/remove/change?
Add the attribute to these newer classes.

## Why do you want to add/remove/change that?
So that there is a unified way to get the name of the provider

## How do you want to go about adding/removing/changing that?
I might put in a PR for this myself, if I find a brief moment to do so.

**Comment by mmaney** [comment]
I take it you're grepping for "dns_provider_name" or something equivalent, since there's a default assignment to that attribute in the base class.  A PR to add an explicit name for those others would be accepted, but of course it would only be applied here to the tip.

As far as I can see, that attribute isn't actually used anywhere in the code base, so it might not be the best choice to rely upon in the long run.

**Comment by komuw** [comment]
@itavero a PR would be welcome

**Comment by mmaney** [comment]
@itavero among other changes already in master, and coming soon in a 0.8.3 release is a JSON catalog that has entries for all drivers, dns and otherwise, with names and descriptions and other data that may well be useful to you.  The dns_provider_name in the drivers is deprecated and will not be added to any new providers going forward.
