### ISSUE TITLE
cryptography.hazmat.primitives.serialization doesn't import

### ISSUE THREAD

**Issue by avkarenow** [komuw/sewer#185]
## Which version of python are you using?
Python 3.8.0

## What operating system and version of operating system are you using?
FreeBSD 11.3

## What version of sewer are you using?
0.8.2

## What did you do? (be as detailed as you can)
When I call client.cert() I got a problem with import:
AttributeError: module 'cryptography.hazmat.primitives' has no attribute 'serialization'

I'm using cryptography 2.9.2

## What did you expect to see/happen/not happen?
Properly import cryptography.hazmat.primitives.serialization

## If you can, run sewer with loglevel set to debug; eg `sewer --loglevel DEBUG`                                           
/virtualenv/lib/python3.8/site-packages/sewer/client.py in get_jwk(self)
    667         """
--> 668         private_key = cryptography.hazmat.primitives.serialization.load_pem_private_key(
    669             self.account_key.encode(),

AttributeError: module 'cryptography.hazmat.primitives' has no attribute 'serialization'

Alternatively if you want to conribute to this repo, answer this questions instead in your issue:                    

## What is it that you would like to propose to add/remove/change?
import cryptography.hazmat.primitives.serialization
in sewer/client.py
It seems to solve the problem, but there is maybe a better way.

**Comment by mmaney** [comment]
Cannot replicate with 3.6 in github's CI runner, 3.7 that was installed here, nor 3.8.0 that I built from source (and because, after having been messing with that for something else this week, I could <wink>).  Of course this is all Linux, indeed it's all Debian-ish (Ubuntu on the runner, with no BSD options).

Try this in the REPL with the sewer package in your path (or running in the directory that contains the sewer package) to, I expect, eliminate some arcane BSD-specific weirdness that I really can't imagine:

import sys, sewer
[m for m in sys.modules.keys() if m.startswith("cryptography")]

I get a list of 66 names, how about you?

If that spits out a long list then I would wonder if there's something odd in the way you're running sewer.  How does your bespoke code load client.py?

Oh, and also curious if this worked with some earlier version of sewer?

**Comment by avkarenow** [comment]
Hello,

thanks for some clues and tests. I found that the problem was caused by the old version of pyOpenSSL (16.2.0) in my virtualenv. I updated it to the latest 19.1.0 and import works as excepted.

I also made some tests on older versions of Python - the same behavior happened.

**Comment by mmaney** [comment]
@avkarenow thanks for following up.  I was actually wondering about a difference in, as best I could guess, requests and what it pulls in from cryptography.  It's clear on the face of it, now that I've actually looked, that client.py is certainly NOT importing what it uses, and this is working as a side effect of some other module that does import things from deep in hazmat.  But I didn't really figure that out until after I'd replied.

Thanks!
