### ISSUE TITLE
ECDSA support

### ISSUE THREAD

**Issue by jfb** [komuw/sewer#202]
## What is it that you would like to propose to add/remove/change?

ECDSA support.

**Comment by mmaney** [comment]
The Pypi release mechanism having been oiled and found to work, I'm turning my attention back to all the things put off in order to make the release.  And I think that I'd like to do a little more than the minimum possible here in order to move towards a better design for the future.  With suitable handwaving...

Freestanding function create_key that takes one of the ECDSA names or a name like RSA2048 and creates the requested type of key.  This can be wired into Client.create_key which will translate the `__init__` parameters into a suitable name for the lib.create_key (though if it has a few friends that could be instead crypto.create_key).  Does this sound reasonable?  Am I skipping the step about wanting to replace the couple of OpenSsl uses in Client with facilities from cryptography?

The as-compatible-as-possible-under-the-circumstances interface... should there be two parameters like your curve, say acct_key_type & cert_key_type?  I don't think there's any reason those keys have to be the same type, and as I understand it there are still reasons why one might wish to have an RSA certificate to fall back to with some less up to date clients?

In the longer view, Client the God-class gets refactored and key creation is no longer its job - calling code, which might still include a more or less compatible get_certificate, would assume that task.  But that's 0.9 talk.  :-)

**Comment by mmaney** [comment]
ECDSA support has sort of arrived in the crypto branch.  As the name suggests, this was more the long-contemplated refactoring of the cryptographic operations that the client uses, and the conversion of some of the operations from OpenSSL to cryptography.  Your PR was something of a trigger here!

I have to get back to some more mundane PRs that are past due some attention.  Once I get those into the 0.8.4 branch I'll be back with, hopefully, some less crude ideas about how to incorporate the options this opens up.

**Comment by mmaney** [comment]
While cleaning up the loose ends (and writing some documentation for the new features), I discovered that LE [staging] is NOT accepting P-521 account certificates either (already knew they didn't process such for certificate keys).  I would swear I tried this the other day and succeeded, but this from a few minutes ago seems definitive:
```'detail': 'ECDSA curve P-521 not allowed'```
Well shoot.  OTOH, that does simplify things in that acct_key and cert_key accepted types are the same again.  :-(

I did find a data-dependent bug in the JWK that seems to only affect EC public keys thanks to this.  It's always one more thing holding up the "last" big push...

**Comment by mmaney** [comment]
Further investigation in lieu of documentation that I could find...

There's no choice of hash for RSA keys:  ```expected one of RS256, ES256, ES384 or ES512```

I lack motivation to try to puzzle why it says here that ES512 is okay, since that's only spec'd to be used with P-521, see above.  At a guess, this is a context-blind error message that only knows that the hash handling code is setup to handle those four.
